# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs


jobs:

  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build application
          command: |
            cd scyrbe_frontend
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker build -t badmusanu/hng-task4-frontend .
            docker push badmusanu/hng-task4-frontend
            cd ../backend/app
            docker build -t badmusanu/hng-task4-frontend .
            docker push badmusanu/hng-task4-frontend
  deploy:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy over SSH
            command: ssh -p your_port_number your_user@your_host "cd ../path/to/your/project; git pull; pm2 start hello_sts";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

